deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: "ais-public-artifacts"
  skip_cleanup: true
  local_dir: exists
  upload-dir: test 
  acl: public_read
  on:
    condition: "-d exists"

branches:
  only:
  - master
